version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: 0000
    ports:
      - "3306:3306"

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
